"""Initial schema

Revision ID: 02af346352f7
Revises: 
Create Date: 2026-08-17 02:30:19.795755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02af346352f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('passport_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lockdown_graduated', sa.Boolean(), nullable=False),
    sa.Column('lockdown_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('care_action_count', sa.Integer(), nullable=False),
    sa.Column('egg_pull_count_today', sa.Integer(), nullable=False),
    sa.Column('last_egg_pull_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_passport_id'), 'users', ['passport_id'], unique=True)
    op.create_table('companions',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('origin_type', sa.String(length=20), nullable=False),
    sa.Column('origin_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('life_stage', sa.String(length=20), nullable=False),
    sa.Column('maturation_progress', sa.Float(), nullable=False),
    sa.Column('base_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mutated_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hidden_genetic_potential', sa.Float(), nullable=False),
    sa.Column('color_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seasonal_pattern', sa.String(length=50), nullable=True),
    sa.Column('personality_type', sa.String(length=50), nullable=False),
    sa.Column('personality_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('behavioral_quirks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bond_level', sa.Integer(), nullable=False),
    sa.Column('care_streak', sa.Integer(), nullable=False),
    sa.Column('parent_a_uuid', sa.UUID(), nullable=True),
    sa.Column('parent_b_uuid', sa.UUID(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(length=20), nullable=False),
    sa.Column('health_status', sa.Float(), nullable=False),
    sa.Column('breeding_cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('on_chain_record', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['parent_a_uuid'], ['companions.uuid'], ),
    sa.ForeignKeyConstraint(['parent_b_uuid'], ['companions.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_companions_user_id'), 'companions', ['user_id'], unique=False)
    op.create_table('currency_ledgers',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('dust_balance', sa.BigInteger(), nullable=False),
    sa.Column('shard_balance', sa.BigInteger(), nullable=False),
    sa.Column('cuboid_balance', sa.BigInteger(), nullable=False),
    sa.Column('ele_balance', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('eggs',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('pulled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hatched', sa.Boolean(), nullable=False),
    sa.Column('hatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hatched_companion_uuid', sa.UUID(), nullable=True),
    sa.Column('incubation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_eggs_user_id'), 'eggs', ['user_id'], unique=False)
    op.create_table('lockdown_states',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('graduated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('care_actions_completed', sa.Integer(), nullable=False),
    sa.Column('min_bond_achieved', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('bond_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('companion_uuid', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('bond_delta', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['companion_uuid'], ['companions.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bond_events_companion_uuid'), 'bond_events', ['companion_uuid'], unique=False)
    op.create_table('care_states',
    sa.Column('companion_uuid', sa.UUID(), nullable=False),
    sa.Column('hunger', sa.Float(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('morale', sa.Float(), nullable=False),
    sa.Column('cleanliness', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['companion_uuid'], ['companions.uuid'], ),
    sa.PrimaryKeyConstraint('companion_uuid')
    )
    op.create_table('expeditions',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('companion_uuid', sa.UUID(), nullable=False),
    sa.Column('biome_zone', sa.String(length=50), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returns_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.Float(), nullable=False),
    sa.Column('loadout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['companion_uuid'], ['companions.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_expeditions_user_id'), 'expeditions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expeditions_user_id'), table_name='expeditions')
    op.drop_table('expeditions')
    op.drop_table('care_states')
    op.drop_index(op.f('ix_bond_events_companion_uuid'), table_name='bond_events')
    op.drop_table('bond_events')
    op.drop_table('lockdown_states')
    op.drop_index(op.f('ix_eggs_user_id'), table_name='eggs')
    op.drop_table('eggs')
    op.drop_table('currency_ledgers')
    op.drop_index(op.f('ix_companions_user_id'), table_name='companions')
    op.drop_table('companions')
    op.drop_index(op.f('ix_users_passport_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
